name: darky-core

services:
  whatpony-bot:
    container_name: whatpony-bot
    environment:
      - TZ=Europe/Moscow
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - darky-network

networks:
  darky-network:
    attachable: true